apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: travelo
  labels:
    app: travelo
    component: frontend
spec:
  # Même politique: au moins 1 pod frontend toujours dispo
  minAvailable: 1
  
  selector:
    matchLabels:
      app: travelo
      component: frontend