apiVersion: v1
kind: ServiceAccount
metadata:
  name: travelo-readonly
  namespace: travelo
  labels:
    app: travelo
    purpose: rbac-demo
# Pas de spec nécessaire pour un ServiceAccount basique
# K8s va créer automatiquement un token associé