apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: travelo
  labels:
    app: travelo
type: Opaque
data:
  # Toutes les valeurs DOIVENT être encodées en base64
  # Pour décoder: echo "cm9vdA==" | base64 --decode
  
  # MySQL root password (utilisé par le pod MySQL)
  MYSQL_ROOT_PASSWORD: cm9vdA==
  
  # Credentials utilisés par Spring Backend pour se connecter à MySQL
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==