apiVersion: v1
kind: ConfigMap
metadata:
  name: travelo-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.config.database | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.springDatasourceUrl | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}