apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.springDatasourcePassword | quote }}