{{- if .Values.security.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: travelo-quota
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.labels" . | nindent 4 }}
spec:
  hard:
    pods: {{ .Values.security.resourceQuota.pods | quote }}
    persistentvolumeclaims: {{ .Values.security.resourceQuota.pvc | quote }}
    services: "5"
    configmaps: "10"
    secrets: "10"
    requests.cpu: {{ .Values.security.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.security.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.security.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.security.resourceQuota.limitsMemory | quote }}
    requests.storage: "10Gi"
{{- end }}