{{- if .Values.security.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: travelo-limits
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "travelo.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "10m"
        memory: "32Mi"
      max:
        cpu: "2000m"
        memory: "2Gi"
      maxLimitRequestRatio:
        cpu: "10"
        memory: "4"
{{- end }}